/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /root/atom_service_dev/server_compiling/db/client/fj_front/idl/StartRequestBInfrared/StartRequestBInfrared.h
  Source: /root/atom_service_dev/server_compiling/db/client/fj_front/idl/StartRequestBInfrared/StartRequestBInfrared.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC__ROOT_ATOM_SERVICE_DEV_SERVER_COMPILING_DB_CLIENT_FJ_FRONT_IDL_STARTREQUESTBINFRARED_STARTREQUESTBINFRARED_H_EF056EB675F0B52DD9A0EDC13C2E968E
#define DDSC__ROOT_ATOM_SERVICE_DEV_SERVER_COMPILING_DB_CLIENT_FJ_FRONT_IDL_STARTREQUESTBINFRARED_STARTREQUESTBINFRARED_H_EF056EB675F0B52DD9A0EDC13C2E968E

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct StartRequestBInfrared_infrared_info
{
  int32_t x;
  int32_t y;
  int32_t z;
  int32_t size;
} StartRequestBInfrared_infrared_info;

extern const dds_topic_descriptor_t StartRequestBInfrared_infrared_info_desc;

#define StartRequestBInfrared_infrared_info__alloc() \
((StartRequestBInfrared_infrared_info*) dds_alloc (sizeof (StartRequestBInfrared_infrared_info)));

#define StartRequestBInfrared_infrared_info_free(d,o) \
dds_sample_free ((d), &StartRequestBInfrared_infrared_info_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__ROOT_ATOM_SERVICE_DEV_SERVER_COMPILING_DB_CLIENT_FJ_FRONT_IDL_STARTREQUESTBINFRARED_STARTREQUESTBINFRARED_H_EF056EB675F0B52DD9A0EDC13C2E968E */
