/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /root/atom_service_dev/server_compiling/db/client/plane_attack/idl/StartRequestInfrared/StartRequestInfrared.h
  Source: /root/atom_service_dev/server_compiling/db/client/plane_attack/idl/StartRequestInfrared/StartRequestInfrared.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC__ROOT_ATOM_SERVICE_DEV_SERVER_COMPILING_DB_CLIENT_PLANE_ATTACK_IDL_STARTREQUESTINFRARED_STARTREQUESTINFRARED_H_BE7835C50C116161B351BB0C8C2E489F
#define DDSC__ROOT_ATOM_SERVICE_DEV_SERVER_COMPILING_DB_CLIENT_PLANE_ATTACK_IDL_STARTREQUESTINFRARED_STARTREQUESTINFRARED_H_BE7835C50C116161B351BB0C8C2E489F

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct StartRequestInfrared_infrared_info
{
  int32_t x;
  int32_t y;
  int32_t z;
  int32_t size;
} StartRequestInfrared_infrared_info;

extern const dds_topic_descriptor_t StartRequestInfrared_infrared_info_desc;

#define StartRequestInfrared_infrared_info__alloc() \
((StartRequestInfrared_infrared_info*) dds_alloc (sizeof (StartRequestInfrared_infrared_info)));

#define StartRequestInfrared_infrared_info_free(d,o) \
dds_sample_free ((d), &StartRequestInfrared_infrared_info_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__ROOT_ATOM_SERVICE_DEV_SERVER_COMPILING_DB_CLIENT_PLANE_ATTACK_IDL_STARTREQUESTINFRARED_STARTREQUESTINFRARED_H_BE7835C50C116161B351BB0C8C2E489F */
