/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /root/micro_service/server_compiling/db/client/SERVICE2/idl/EndResponse/EndResponse.h
  Source: /root/micro_service/server_compiling/db/client/SERVICE2/idl/EndResponse/EndResponse.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC__ROOT_MICRO_SERVICE_SERVER_COMPILING_DB_CLIENT_SERVICE2_IDL_ENDRESPONSE_ENDRESPONSE_H_2CF10FC1DE047B51BD8CABD24A14FB53
#define DDSC__ROOT_MICRO_SERVICE_SERVER_COMPILING_DB_CLIENT_SERVICE2_IDL_ENDRESPONSE_ENDRESPONSE_H_2CF10FC1DE047B51BD8CABD24A14FB53

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct EndResponse_atomic_service_sf_task_E_Reply_st
{
  int32_t sum_result;
  int32_t return_type;
} EndResponse_atomic_service_sf_task_E_Reply_st;

extern const dds_topic_descriptor_t EndResponse_atomic_service_sf_task_E_Reply_st_desc;

#define EndResponse_atomic_service_sf_task_E_Reply_st__alloc() \
((EndResponse_atomic_service_sf_task_E_Reply_st*) dds_alloc (sizeof (EndResponse_atomic_service_sf_task_E_Reply_st)));

#define EndResponse_atomic_service_sf_task_E_Reply_st_free(d,o) \
dds_sample_free ((d), &EndResponse_atomic_service_sf_task_E_Reply_st_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__ROOT_MICRO_SERVICE_SERVER_COMPILING_DB_CLIENT_SERVICE2_IDL_ENDRESPONSE_ENDRESPONSE_H_2CF10FC1DE047B51BD8CABD24A14FB53 */
