// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: atomic_service_mbsb.proto
#ifndef GRPC_atomic_5fservice_5fmbsb_2eproto__INCLUDED
#define GRPC_atomic_5fservice_5fmbsb_2eproto__INCLUDED

#include "atomic_service_mbsb.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace atomic_service_mbsb_Package {

class atomic_service_mbsb_Service final {
 public:
  static constexpr char const* service_full_name() {
    return "atomic_service_mbsb_Package.atomic_service_mbsb_Service";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status atomic_service_fun_task_A(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>> Asyncatomic_service_fun_task_A(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>>(Asyncatomic_service_fun_task_ARaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>> PrepareAsyncatomic_service_fun_task_A(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>>(PrepareAsyncatomic_service_fun_task_ARaw(context, request, cq));
    }
    virtual ::grpc::Status atomic_service_fun_task_B(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>> Asyncatomic_service_fun_task_B(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>>(Asyncatomic_service_fun_task_BRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>> PrepareAsyncatomic_service_fun_task_B(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>>(PrepareAsyncatomic_service_fun_task_BRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>* Asyncatomic_service_fun_task_ARaw(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>* PrepareAsyncatomic_service_fun_task_ARaw(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>* Asyncatomic_service_fun_task_BRaw(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>* PrepareAsyncatomic_service_fun_task_BRaw(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status atomic_service_fun_task_A(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>> Asyncatomic_service_fun_task_A(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>>(Asyncatomic_service_fun_task_ARaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>> PrepareAsyncatomic_service_fun_task_A(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>>(PrepareAsyncatomic_service_fun_task_ARaw(context, request, cq));
    }
    ::grpc::Status atomic_service_fun_task_B(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>> Asyncatomic_service_fun_task_B(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>>(Asyncatomic_service_fun_task_BRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>> PrepareAsyncatomic_service_fun_task_B(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>>(PrepareAsyncatomic_service_fun_task_BRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>* Asyncatomic_service_fun_task_ARaw(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>* PrepareAsyncatomic_service_fun_task_ARaw(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>* Asyncatomic_service_fun_task_BRaw(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>* PrepareAsyncatomic_service_fun_task_BRaw(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_atomic_service_fun_task_A_;
    const ::grpc::internal::RpcMethod rpcmethod_atomic_service_fun_task_B_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status atomic_service_fun_task_A(::grpc::ServerContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* response);
    virtual ::grpc::Status atomic_service_fun_task_B(::grpc::ServerContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_atomic_service_fun_task_A : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_atomic_service_fun_task_A() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_atomic_service_fun_task_A() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status atomic_service_fun_task_A(::grpc::ServerContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestatomic_service_fun_task_A(::grpc::ServerContext* context, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* request, ::grpc::ServerAsyncResponseWriter< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_atomic_service_fun_task_B : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_atomic_service_fun_task_B() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_atomic_service_fun_task_B() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status atomic_service_fun_task_B(::grpc::ServerContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestatomic_service_fun_task_B(::grpc::ServerContext* context, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* request, ::grpc::ServerAsyncResponseWriter< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_atomic_service_fun_task_A<WithAsyncMethod_atomic_service_fun_task_B<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_atomic_service_fun_task_A : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_atomic_service_fun_task_A() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_atomic_service_fun_task_A() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status atomic_service_fun_task_A(::grpc::ServerContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_atomic_service_fun_task_B : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_atomic_service_fun_task_B() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_atomic_service_fun_task_B() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status atomic_service_fun_task_B(::grpc::ServerContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_atomic_service_fun_task_A : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_atomic_service_fun_task_A() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>(std::bind(&WithStreamedUnaryMethod_atomic_service_fun_task_A<BaseClass>::Streamedatomic_service_fun_task_A, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_atomic_service_fun_task_A() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status atomic_service_fun_task_A(::grpc::ServerContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedatomic_service_fun_task_A(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st,::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_atomic_service_fun_task_B : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_atomic_service_fun_task_B() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>(std::bind(&WithStreamedUnaryMethod_atomic_service_fun_task_B<BaseClass>::Streamedatomic_service_fun_task_B, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_atomic_service_fun_task_B() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status atomic_service_fun_task_B(::grpc::ServerContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedatomic_service_fun_task_B(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st,::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_atomic_service_fun_task_A<WithStreamedUnaryMethod_atomic_service_fun_task_B<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_atomic_service_fun_task_A<WithStreamedUnaryMethod_atomic_service_fun_task_B<Service > > StreamedService;
};

}  // namespace atomic_service_mbsb_Package


#endif  // GRPC_atomic_5fservice_5fmbsb_2eproto__INCLUDED
