// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: atomic_service_mbsb.proto

#ifndef PROTOBUF_INCLUDED_atomic_5fservice_5fmbsb_2eproto
#define PROTOBUF_INCLUDED_atomic_5fservice_5fmbsb_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_atomic_5fservice_5fmbsb_2eproto 

namespace protobuf_atomic_5fservice_5fmbsb_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_atomic_5fservice_5fmbsb_2eproto
namespace atomic_service_mbsb_Package {
class atomic_service_mbsb_Reply_st;
class atomic_service_mbsb_Reply_stDefaultTypeInternal;
extern atomic_service_mbsb_Reply_stDefaultTypeInternal _atomic_service_mbsb_Reply_st_default_instance_;
class atomic_service_mbsb_Request_st;
class atomic_service_mbsb_Request_stDefaultTypeInternal;
extern atomic_service_mbsb_Request_stDefaultTypeInternal _atomic_service_mbsb_Request_st_default_instance_;
}  // namespace atomic_service_mbsb_Package
namespace google {
namespace protobuf {
template<> ::atomic_service_mbsb_Package::atomic_service_mbsb_Reply_st* Arena::CreateMaybeMessage<::atomic_service_mbsb_Package::atomic_service_mbsb_Reply_st>(Arena*);
template<> ::atomic_service_mbsb_Package::atomic_service_mbsb_Request_st* Arena::CreateMaybeMessage<::atomic_service_mbsb_Package::atomic_service_mbsb_Request_st>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace atomic_service_mbsb_Package {

// ===================================================================

class atomic_service_mbsb_Request_st : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:atomic_service_mbsb_Package.atomic_service_mbsb_Request_st) */ {
 public:
  atomic_service_mbsb_Request_st();
  virtual ~atomic_service_mbsb_Request_st();

  atomic_service_mbsb_Request_st(const atomic_service_mbsb_Request_st& from);

  inline atomic_service_mbsb_Request_st& operator=(const atomic_service_mbsb_Request_st& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  atomic_service_mbsb_Request_st(atomic_service_mbsb_Request_st&& from) noexcept
    : atomic_service_mbsb_Request_st() {
    *this = ::std::move(from);
  }

  inline atomic_service_mbsb_Request_st& operator=(atomic_service_mbsb_Request_st&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const atomic_service_mbsb_Request_st& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const atomic_service_mbsb_Request_st* internal_default_instance() {
    return reinterpret_cast<const atomic_service_mbsb_Request_st*>(
               &_atomic_service_mbsb_Request_st_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(atomic_service_mbsb_Request_st* other);
  friend void swap(atomic_service_mbsb_Request_st& a, atomic_service_mbsb_Request_st& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline atomic_service_mbsb_Request_st* New() const final {
    return CreateMaybeMessage<atomic_service_mbsb_Request_st>(NULL);
  }

  atomic_service_mbsb_Request_st* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<atomic_service_mbsb_Request_st>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const atomic_service_mbsb_Request_st& from);
  void MergeFrom(const atomic_service_mbsb_Request_st& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(atomic_service_mbsb_Request_st* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // double double_field = 3;
  void clear_double_field();
  static const int kDoubleFieldFieldNumber = 3;
  double double_field() const;
  void set_double_field(double value);

  // int32 integer_field = 2;
  void clear_integer_field();
  static const int kIntegerFieldFieldNumber = 2;
  ::google::protobuf::int32 integer_field() const;
  void set_integer_field(::google::protobuf::int32 value);

  // float float_field = 4;
  void clear_float_field();
  static const int kFloatFieldFieldNumber = 4;
  float float_field() const;
  void set_float_field(float value);

  // @@protoc_insertion_point(class_scope:atomic_service_mbsb_Package.atomic_service_mbsb_Request_st)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  double double_field_;
  ::google::protobuf::int32 integer_field_;
  float float_field_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_atomic_5fservice_5fmbsb_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class atomic_service_mbsb_Reply_st : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:atomic_service_mbsb_Package.atomic_service_mbsb_Reply_st) */ {
 public:
  atomic_service_mbsb_Reply_st();
  virtual ~atomic_service_mbsb_Reply_st();

  atomic_service_mbsb_Reply_st(const atomic_service_mbsb_Reply_st& from);

  inline atomic_service_mbsb_Reply_st& operator=(const atomic_service_mbsb_Reply_st& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  atomic_service_mbsb_Reply_st(atomic_service_mbsb_Reply_st&& from) noexcept
    : atomic_service_mbsb_Reply_st() {
    *this = ::std::move(from);
  }

  inline atomic_service_mbsb_Reply_st& operator=(atomic_service_mbsb_Reply_st&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const atomic_service_mbsb_Reply_st& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const atomic_service_mbsb_Reply_st* internal_default_instance() {
    return reinterpret_cast<const atomic_service_mbsb_Reply_st*>(
               &_atomic_service_mbsb_Reply_st_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(atomic_service_mbsb_Reply_st* other);
  friend void swap(atomic_service_mbsb_Reply_st& a, atomic_service_mbsb_Reply_st& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline atomic_service_mbsb_Reply_st* New() const final {
    return CreateMaybeMessage<atomic_service_mbsb_Reply_st>(NULL);
  }

  atomic_service_mbsb_Reply_st* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<atomic_service_mbsb_Reply_st>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const atomic_service_mbsb_Reply_st& from);
  void MergeFrom(const atomic_service_mbsb_Reply_st& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(atomic_service_mbsb_Reply_st* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 1;
  void clear_message();
  static const int kMessageFieldNumber = 1;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // double double_reply = 3;
  void clear_double_reply();
  static const int kDoubleReplyFieldNumber = 3;
  double double_reply() const;
  void set_double_reply(double value);

  // int32 integer_reply = 2;
  void clear_integer_reply();
  static const int kIntegerReplyFieldNumber = 2;
  ::google::protobuf::int32 integer_reply() const;
  void set_integer_reply(::google::protobuf::int32 value);

  // float float_reply = 4;
  void clear_float_reply();
  static const int kFloatReplyFieldNumber = 4;
  float float_reply() const;
  void set_float_reply(float value);

  // @@protoc_insertion_point(class_scope:atomic_service_mbsb_Package.atomic_service_mbsb_Reply_st)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  double double_reply_;
  ::google::protobuf::int32 integer_reply_;
  float float_reply_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_atomic_5fservice_5fmbsb_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// atomic_service_mbsb_Request_st

// string name = 1;
inline void atomic_service_mbsb_Request_st::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& atomic_service_mbsb_Request_st::name() const {
  // @@protoc_insertion_point(field_get:atomic_service_mbsb_Package.atomic_service_mbsb_Request_st.name)
  return name_.GetNoArena();
}
inline void atomic_service_mbsb_Request_st::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:atomic_service_mbsb_Package.atomic_service_mbsb_Request_st.name)
}
#if LANG_CXX11
inline void atomic_service_mbsb_Request_st::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:atomic_service_mbsb_Package.atomic_service_mbsb_Request_st.name)
}
#endif
inline void atomic_service_mbsb_Request_st::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:atomic_service_mbsb_Package.atomic_service_mbsb_Request_st.name)
}
inline void atomic_service_mbsb_Request_st::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:atomic_service_mbsb_Package.atomic_service_mbsb_Request_st.name)
}
inline ::std::string* atomic_service_mbsb_Request_st::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:atomic_service_mbsb_Package.atomic_service_mbsb_Request_st.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* atomic_service_mbsb_Request_st::release_name() {
  // @@protoc_insertion_point(field_release:atomic_service_mbsb_Package.atomic_service_mbsb_Request_st.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void atomic_service_mbsb_Request_st::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:atomic_service_mbsb_Package.atomic_service_mbsb_Request_st.name)
}

// int32 integer_field = 2;
inline void atomic_service_mbsb_Request_st::clear_integer_field() {
  integer_field_ = 0;
}
inline ::google::protobuf::int32 atomic_service_mbsb_Request_st::integer_field() const {
  // @@protoc_insertion_point(field_get:atomic_service_mbsb_Package.atomic_service_mbsb_Request_st.integer_field)
  return integer_field_;
}
inline void atomic_service_mbsb_Request_st::set_integer_field(::google::protobuf::int32 value) {
  
  integer_field_ = value;
  // @@protoc_insertion_point(field_set:atomic_service_mbsb_Package.atomic_service_mbsb_Request_st.integer_field)
}

// double double_field = 3;
inline void atomic_service_mbsb_Request_st::clear_double_field() {
  double_field_ = 0;
}
inline double atomic_service_mbsb_Request_st::double_field() const {
  // @@protoc_insertion_point(field_get:atomic_service_mbsb_Package.atomic_service_mbsb_Request_st.double_field)
  return double_field_;
}
inline void atomic_service_mbsb_Request_st::set_double_field(double value) {
  
  double_field_ = value;
  // @@protoc_insertion_point(field_set:atomic_service_mbsb_Package.atomic_service_mbsb_Request_st.double_field)
}

// float float_field = 4;
inline void atomic_service_mbsb_Request_st::clear_float_field() {
  float_field_ = 0;
}
inline float atomic_service_mbsb_Request_st::float_field() const {
  // @@protoc_insertion_point(field_get:atomic_service_mbsb_Package.atomic_service_mbsb_Request_st.float_field)
  return float_field_;
}
inline void atomic_service_mbsb_Request_st::set_float_field(float value) {
  
  float_field_ = value;
  // @@protoc_insertion_point(field_set:atomic_service_mbsb_Package.atomic_service_mbsb_Request_st.float_field)
}

// -------------------------------------------------------------------

// atomic_service_mbsb_Reply_st

// string message = 1;
inline void atomic_service_mbsb_Reply_st::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& atomic_service_mbsb_Reply_st::message() const {
  // @@protoc_insertion_point(field_get:atomic_service_mbsb_Package.atomic_service_mbsb_Reply_st.message)
  return message_.GetNoArena();
}
inline void atomic_service_mbsb_Reply_st::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:atomic_service_mbsb_Package.atomic_service_mbsb_Reply_st.message)
}
#if LANG_CXX11
inline void atomic_service_mbsb_Reply_st::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:atomic_service_mbsb_Package.atomic_service_mbsb_Reply_st.message)
}
#endif
inline void atomic_service_mbsb_Reply_st::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:atomic_service_mbsb_Package.atomic_service_mbsb_Reply_st.message)
}
inline void atomic_service_mbsb_Reply_st::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:atomic_service_mbsb_Package.atomic_service_mbsb_Reply_st.message)
}
inline ::std::string* atomic_service_mbsb_Reply_st::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:atomic_service_mbsb_Package.atomic_service_mbsb_Reply_st.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* atomic_service_mbsb_Reply_st::release_message() {
  // @@protoc_insertion_point(field_release:atomic_service_mbsb_Package.atomic_service_mbsb_Reply_st.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void atomic_service_mbsb_Reply_st::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:atomic_service_mbsb_Package.atomic_service_mbsb_Reply_st.message)
}

// int32 integer_reply = 2;
inline void atomic_service_mbsb_Reply_st::clear_integer_reply() {
  integer_reply_ = 0;
}
inline ::google::protobuf::int32 atomic_service_mbsb_Reply_st::integer_reply() const {
  // @@protoc_insertion_point(field_get:atomic_service_mbsb_Package.atomic_service_mbsb_Reply_st.integer_reply)
  return integer_reply_;
}
inline void atomic_service_mbsb_Reply_st::set_integer_reply(::google::protobuf::int32 value) {
  
  integer_reply_ = value;
  // @@protoc_insertion_point(field_set:atomic_service_mbsb_Package.atomic_service_mbsb_Reply_st.integer_reply)
}

// double double_reply = 3;
inline void atomic_service_mbsb_Reply_st::clear_double_reply() {
  double_reply_ = 0;
}
inline double atomic_service_mbsb_Reply_st::double_reply() const {
  // @@protoc_insertion_point(field_get:atomic_service_mbsb_Package.atomic_service_mbsb_Reply_st.double_reply)
  return double_reply_;
}
inline void atomic_service_mbsb_Reply_st::set_double_reply(double value) {
  
  double_reply_ = value;
  // @@protoc_insertion_point(field_set:atomic_service_mbsb_Package.atomic_service_mbsb_Reply_st.double_reply)
}

// float float_reply = 4;
inline void atomic_service_mbsb_Reply_st::clear_float_reply() {
  float_reply_ = 0;
}
inline float atomic_service_mbsb_Reply_st::float_reply() const {
  // @@protoc_insertion_point(field_get:atomic_service_mbsb_Package.atomic_service_mbsb_Reply_st.float_reply)
  return float_reply_;
}
inline void atomic_service_mbsb_Reply_st::set_float_reply(float value) {
  
  float_reply_ = value;
  // @@protoc_insertion_point(field_set:atomic_service_mbsb_Package.atomic_service_mbsb_Reply_st.float_reply)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace atomic_service_mbsb_Package

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_atomic_5fservice_5fmbsb_2eproto
