// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: atomic_service_mbsb.proto
#ifndef GRPC_atomic_5fservice_5fmbsb_2eproto__INCLUDED
#define GRPC_atomic_5fservice_5fmbsb_2eproto__INCLUDED

#include "atomic_service_mbsb.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace atomic_service_mbsb_Package {

class atomic_service_mbsb_Service final {
 public:
  static constexpr char const* service_full_name() {
    return "atomic_service_mbsb_Package.atomic_service_mbsb_Service";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status atomic_service_fun_task_A(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>> Asyncatomic_service_fun_task_A(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>>(Asyncatomic_service_fun_task_ARaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>> PrepareAsyncatomic_service_fun_task_A(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>>(PrepareAsyncatomic_service_fun_task_ARaw(context, request, cq));
    }
    virtual ::grpc::Status atomic_service_fun_task_B(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>> Asyncatomic_service_fun_task_B(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>>(Asyncatomic_service_fun_task_BRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>> PrepareAsyncatomic_service_fun_task_B(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>>(PrepareAsyncatomic_service_fun_task_BRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void atomic_service_fun_task_A(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* response, std::function<void(::grpc::Status)>) = 0;
      virtual void atomic_service_fun_task_A(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void atomic_service_fun_task_B(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* response, std::function<void(::grpc::Status)>) = 0;
      virtual void atomic_service_fun_task_B(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>* Asyncatomic_service_fun_task_ARaw(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>* PrepareAsyncatomic_service_fun_task_ARaw(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>* Asyncatomic_service_fun_task_BRaw(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>* PrepareAsyncatomic_service_fun_task_BRaw(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status atomic_service_fun_task_A(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>> Asyncatomic_service_fun_task_A(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>>(Asyncatomic_service_fun_task_ARaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>> PrepareAsyncatomic_service_fun_task_A(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>>(PrepareAsyncatomic_service_fun_task_ARaw(context, request, cq));
    }
    ::grpc::Status atomic_service_fun_task_B(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>> Asyncatomic_service_fun_task_B(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>>(Asyncatomic_service_fun_task_BRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>> PrepareAsyncatomic_service_fun_task_B(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>>(PrepareAsyncatomic_service_fun_task_BRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void atomic_service_fun_task_A(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* response, std::function<void(::grpc::Status)>) override;
      void atomic_service_fun_task_A(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* response, ::grpc::ClientUnaryReactor* reactor) override;
      void atomic_service_fun_task_B(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* response, std::function<void(::grpc::Status)>) override;
      void atomic_service_fun_task_B(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>* Asyncatomic_service_fun_task_ARaw(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>* PrepareAsyncatomic_service_fun_task_ARaw(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>* Asyncatomic_service_fun_task_BRaw(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>* PrepareAsyncatomic_service_fun_task_BRaw(::grpc::ClientContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_atomic_service_fun_task_A_;
    const ::grpc::internal::RpcMethod rpcmethod_atomic_service_fun_task_B_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status atomic_service_fun_task_A(::grpc::ServerContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* response);
    virtual ::grpc::Status atomic_service_fun_task_B(::grpc::ServerContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_atomic_service_fun_task_A : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_atomic_service_fun_task_A() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_atomic_service_fun_task_A() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status atomic_service_fun_task_A(::grpc::ServerContext* /*context*/, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* /*request*/, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestatomic_service_fun_task_A(::grpc::ServerContext* context, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* request, ::grpc::ServerAsyncResponseWriter< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_atomic_service_fun_task_B : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_atomic_service_fun_task_B() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_atomic_service_fun_task_B() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status atomic_service_fun_task_B(::grpc::ServerContext* /*context*/, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* /*request*/, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestatomic_service_fun_task_B(::grpc::ServerContext* context, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* request, ::grpc::ServerAsyncResponseWriter< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_atomic_service_fun_task_A<WithAsyncMethod_atomic_service_fun_task_B<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_atomic_service_fun_task_A : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_atomic_service_fun_task_A() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* response) { return this->atomic_service_fun_task_A(context, request, response); }));}
    void SetMessageAllocatorFor_atomic_service_fun_task_A(
        ::grpc::MessageAllocator< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_atomic_service_fun_task_A() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status atomic_service_fun_task_A(::grpc::ServerContext* /*context*/, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* /*request*/, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* atomic_service_fun_task_A(
      ::grpc::CallbackServerContext* /*context*/, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* /*request*/, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_atomic_service_fun_task_B : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_atomic_service_fun_task_B() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* request, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* response) { return this->atomic_service_fun_task_B(context, request, response); }));}
    void SetMessageAllocatorFor_atomic_service_fun_task_B(
        ::grpc::MessageAllocator< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_atomic_service_fun_task_B() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status atomic_service_fun_task_B(::grpc::ServerContext* /*context*/, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* /*request*/, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* atomic_service_fun_task_B(
      ::grpc::CallbackServerContext* /*context*/, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* /*request*/, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_atomic_service_fun_task_A<WithCallbackMethod_atomic_service_fun_task_B<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_atomic_service_fun_task_A : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_atomic_service_fun_task_A() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_atomic_service_fun_task_A() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status atomic_service_fun_task_A(::grpc::ServerContext* /*context*/, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* /*request*/, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_atomic_service_fun_task_B : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_atomic_service_fun_task_B() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_atomic_service_fun_task_B() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status atomic_service_fun_task_B(::grpc::ServerContext* /*context*/, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* /*request*/, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_atomic_service_fun_task_A : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_atomic_service_fun_task_A() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_atomic_service_fun_task_A() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status atomic_service_fun_task_A(::grpc::ServerContext* /*context*/, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* /*request*/, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestatomic_service_fun_task_A(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_atomic_service_fun_task_B : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_atomic_service_fun_task_B() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_atomic_service_fun_task_B() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status atomic_service_fun_task_B(::grpc::ServerContext* /*context*/, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* /*request*/, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestatomic_service_fun_task_B(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_atomic_service_fun_task_A : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_atomic_service_fun_task_A() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->atomic_service_fun_task_A(context, request, response); }));
    }
    ~WithRawCallbackMethod_atomic_service_fun_task_A() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status atomic_service_fun_task_A(::grpc::ServerContext* /*context*/, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* /*request*/, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* atomic_service_fun_task_A(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_atomic_service_fun_task_B : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_atomic_service_fun_task_B() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->atomic_service_fun_task_B(context, request, response); }));
    }
    ~WithRawCallbackMethod_atomic_service_fun_task_B() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status atomic_service_fun_task_B(::grpc::ServerContext* /*context*/, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* /*request*/, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* atomic_service_fun_task_B(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_atomic_service_fun_task_A : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_atomic_service_fun_task_A() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>* streamer) {
                       return this->Streamedatomic_service_fun_task_A(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_atomic_service_fun_task_A() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status atomic_service_fun_task_A(::grpc::ServerContext* /*context*/, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st* /*request*/, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedatomic_service_fun_task_A(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st,::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_atomic_service_fun_task_B : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_atomic_service_fun_task_B() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>* streamer) {
                       return this->Streamedatomic_service_fun_task_B(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_atomic_service_fun_task_B() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status atomic_service_fun_task_B(::grpc::ServerContext* /*context*/, const ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st* /*request*/, ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedatomic_service_fun_task_B(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st,::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_atomic_service_fun_task_A<WithStreamedUnaryMethod_atomic_service_fun_task_B<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_atomic_service_fun_task_A<WithStreamedUnaryMethod_atomic_service_fun_task_B<Service > > StreamedService;
};

}  // namespace atomic_service_mbsb_Package


#endif  // GRPC_atomic_5fservice_5fmbsb_2eproto__INCLUDED
