// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: atomic_service_mbsb.proto
// Protobuf C++ Version: 5.29.0

#include "atomic_service_mbsb.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace atomic_service_mbsb_Package {

inline constexpr atomic_service_mbsb_task_B_Request_st::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : number1_{0},
        number2_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR atomic_service_mbsb_task_B_Request_st::atomic_service_mbsb_task_B_Request_st(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct atomic_service_mbsb_task_B_Request_stDefaultTypeInternal {
  PROTOBUF_CONSTEXPR atomic_service_mbsb_task_B_Request_stDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~atomic_service_mbsb_task_B_Request_stDefaultTypeInternal() {}
  union {
    atomic_service_mbsb_task_B_Request_st _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 atomic_service_mbsb_task_B_Request_stDefaultTypeInternal _atomic_service_mbsb_task_B_Request_st_default_instance_;

inline constexpr atomic_service_mbsb_task_B_Reply_st::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : sub_result_{0},
        return_type_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR atomic_service_mbsb_task_B_Reply_st::atomic_service_mbsb_task_B_Reply_st(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct atomic_service_mbsb_task_B_Reply_stDefaultTypeInternal {
  PROTOBUF_CONSTEXPR atomic_service_mbsb_task_B_Reply_stDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~atomic_service_mbsb_task_B_Reply_stDefaultTypeInternal() {}
  union {
    atomic_service_mbsb_task_B_Reply_st _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 atomic_service_mbsb_task_B_Reply_stDefaultTypeInternal _atomic_service_mbsb_task_B_Reply_st_default_instance_;

inline constexpr atomic_service_mbsb_task_A_Request_st::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : number1_{0},
        number2_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR atomic_service_mbsb_task_A_Request_st::atomic_service_mbsb_task_A_Request_st(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct atomic_service_mbsb_task_A_Request_stDefaultTypeInternal {
  PROTOBUF_CONSTEXPR atomic_service_mbsb_task_A_Request_stDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~atomic_service_mbsb_task_A_Request_stDefaultTypeInternal() {}
  union {
    atomic_service_mbsb_task_A_Request_st _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 atomic_service_mbsb_task_A_Request_stDefaultTypeInternal _atomic_service_mbsb_task_A_Request_st_default_instance_;

inline constexpr atomic_service_mbsb_task_A_Reply_st::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : sum_result_{0},
        return_type_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR atomic_service_mbsb_task_A_Reply_st::atomic_service_mbsb_task_A_Reply_st(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct atomic_service_mbsb_task_A_Reply_stDefaultTypeInternal {
  PROTOBUF_CONSTEXPR atomic_service_mbsb_task_A_Reply_stDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~atomic_service_mbsb_task_A_Reply_stDefaultTypeInternal() {}
  union {
    atomic_service_mbsb_task_A_Reply_st _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 atomic_service_mbsb_task_A_Reply_stDefaultTypeInternal _atomic_service_mbsb_task_A_Reply_st_default_instance_;
}  // namespace atomic_service_mbsb_Package
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_atomic_5fservice_5fmbsb_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_atomic_5fservice_5fmbsb_2eproto = nullptr;
const ::uint32_t
    TableStruct_atomic_5fservice_5fmbsb_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st, _impl_.number1_),
        PROTOBUF_FIELD_OFFSET(::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st, _impl_.number2_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st, _impl_.sum_result_),
        PROTOBUF_FIELD_OFFSET(::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st, _impl_.return_type_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st, _impl_.number1_),
        PROTOBUF_FIELD_OFFSET(::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st, _impl_.number2_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st, _impl_.sub_result_),
        PROTOBUF_FIELD_OFFSET(::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st, _impl_.return_type_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st)},
        {10, -1, -1, sizeof(::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st)},
        {20, -1, -1, sizeof(::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st)},
        {30, -1, -1, sizeof(::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::atomic_service_mbsb_Package::_atomic_service_mbsb_task_A_Request_st_default_instance_._instance,
    &::atomic_service_mbsb_Package::_atomic_service_mbsb_task_A_Reply_st_default_instance_._instance,
    &::atomic_service_mbsb_Package::_atomic_service_mbsb_task_B_Request_st_default_instance_._instance,
    &::atomic_service_mbsb_Package::_atomic_service_mbsb_task_B_Reply_st_default_instance_._instance,
};
const char descriptor_table_protodef_atomic_5fservice_5fmbsb_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\031atomic_service_mbsb.proto\022\033atomic_serv"
    "ice_mbsb_Package\"I\n%atomic_service_mbsb_"
    "task_A_Request_st\022\017\n\007number1\030\001 \001(\005\022\017\n\007nu"
    "mber2\030\002 \001(\005\"N\n#atomic_service_mbsb_task_"
    "A_Reply_st\022\022\n\nsum_result\030\001 \001(\005\022\023\n\013return"
    "_type\030\002 \001(\005\"I\n%atomic_service_mbsb_task_"
    "B_Request_st\022\017\n\007number1\030\001 \001(\005\022\017\n\007number2"
    "\030\002 \001(\005\"N\n#atomic_service_mbsb_task_B_Rep"
    "ly_st\022\022\n\nsub_result\030\001 \001(\005\022\023\n\013return_type"
    "\030\002 \001(\0052\351\002\n\033atomic_service_mbsb_Service\022\243"
    "\001\n\031atomic_service_fun_task_A\022B.atomic_se"
    "rvice_mbsb_Package.atomic_service_mbsb_t"
    "ask_A_Request_st\032@.atomic_service_mbsb_P"
    "ackage.atomic_service_mbsb_task_A_Reply_"
    "st\"\000\022\243\001\n\031atomic_service_fun_task_B\022B.ato"
    "mic_service_mbsb_Package.atomic_service_"
    "mbsb_task_B_Request_st\032@.atomic_service_"
    "mbsb_Package.atomic_service_mbsb_task_B_"
    "Reply_st\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_atomic_5fservice_5fmbsb_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_atomic_5fservice_5fmbsb_2eproto = {
    false,
    false,
    738,
    descriptor_table_protodef_atomic_5fservice_5fmbsb_2eproto,
    "atomic_service_mbsb.proto",
    &descriptor_table_atomic_5fservice_5fmbsb_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_atomic_5fservice_5fmbsb_2eproto::offsets,
    file_level_enum_descriptors_atomic_5fservice_5fmbsb_2eproto,
    file_level_service_descriptors_atomic_5fservice_5fmbsb_2eproto,
};
namespace atomic_service_mbsb_Package {
// ===================================================================

class atomic_service_mbsb_task_A_Request_st::_Internal {
 public:
};

atomic_service_mbsb_task_A_Request_st::atomic_service_mbsb_task_A_Request_st(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Request_st)
}
atomic_service_mbsb_task_A_Request_st::atomic_service_mbsb_task_A_Request_st(
    ::google::protobuf::Arena* arena, const atomic_service_mbsb_task_A_Request_st& from)
    : atomic_service_mbsb_task_A_Request_st(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE atomic_service_mbsb_task_A_Request_st::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void atomic_service_mbsb_task_A_Request_st::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, number1_),
           0,
           offsetof(Impl_, number2_) -
               offsetof(Impl_, number1_) +
               sizeof(Impl_::number2_));
}
atomic_service_mbsb_task_A_Request_st::~atomic_service_mbsb_task_A_Request_st() {
  // @@protoc_insertion_point(destructor:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Request_st)
  SharedDtor(*this);
}
inline void atomic_service_mbsb_task_A_Request_st::SharedDtor(MessageLite& self) {
  atomic_service_mbsb_task_A_Request_st& this_ = static_cast<atomic_service_mbsb_task_A_Request_st&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* atomic_service_mbsb_task_A_Request_st::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) atomic_service_mbsb_task_A_Request_st(arena);
}
constexpr auto atomic_service_mbsb_task_A_Request_st::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(atomic_service_mbsb_task_A_Request_st),
                                            alignof(atomic_service_mbsb_task_A_Request_st));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull atomic_service_mbsb_task_A_Request_st::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_atomic_service_mbsb_task_A_Request_st_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &atomic_service_mbsb_task_A_Request_st::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<atomic_service_mbsb_task_A_Request_st>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &atomic_service_mbsb_task_A_Request_st::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<atomic_service_mbsb_task_A_Request_st>(), &atomic_service_mbsb_task_A_Request_st::ByteSizeLong,
            &atomic_service_mbsb_task_A_Request_st::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_A_Request_st, _impl_._cached_size_),
        false,
    },
    &atomic_service_mbsb_task_A_Request_st::kDescriptorMethods,
    &descriptor_table_atomic_5fservice_5fmbsb_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* atomic_service_mbsb_task_A_Request_st::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> atomic_service_mbsb_task_A_Request_st::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Request_st>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 number2 = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(atomic_service_mbsb_task_A_Request_st, _impl_.number2_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_A_Request_st, _impl_.number2_)}},
    // int32 number1 = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(atomic_service_mbsb_task_A_Request_st, _impl_.number1_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_A_Request_st, _impl_.number1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 number1 = 1;
    {PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_A_Request_st, _impl_.number1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 number2 = 2;
    {PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_A_Request_st, _impl_.number2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void atomic_service_mbsb_task_A_Request_st::Clear() {
// @@protoc_insertion_point(message_clear_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Request_st)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.number1_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.number2_) -
      reinterpret_cast<char*>(&_impl_.number1_)) + sizeof(_impl_.number2_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* atomic_service_mbsb_task_A_Request_st::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const atomic_service_mbsb_task_A_Request_st& this_ = static_cast<const atomic_service_mbsb_task_A_Request_st&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* atomic_service_mbsb_task_A_Request_st::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const atomic_service_mbsb_task_A_Request_st& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Request_st)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 number1 = 1;
          if (this_._internal_number1() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_number1(), target);
          }

          // int32 number2 = 2;
          if (this_._internal_number2() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_number2(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Request_st)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t atomic_service_mbsb_task_A_Request_st::ByteSizeLong(const MessageLite& base) {
          const atomic_service_mbsb_task_A_Request_st& this_ = static_cast<const atomic_service_mbsb_task_A_Request_st&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t atomic_service_mbsb_task_A_Request_st::ByteSizeLong() const {
          const atomic_service_mbsb_task_A_Request_st& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Request_st)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 number1 = 1;
            if (this_._internal_number1() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_number1());
            }
            // int32 number2 = 2;
            if (this_._internal_number2() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_number2());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void atomic_service_mbsb_task_A_Request_st::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<atomic_service_mbsb_task_A_Request_st*>(&to_msg);
  auto& from = static_cast<const atomic_service_mbsb_task_A_Request_st&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Request_st)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_number1() != 0) {
    _this->_impl_.number1_ = from._impl_.number1_;
  }
  if (from._internal_number2() != 0) {
    _this->_impl_.number2_ = from._impl_.number2_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void atomic_service_mbsb_task_A_Request_st::CopyFrom(const atomic_service_mbsb_task_A_Request_st& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Request_st)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void atomic_service_mbsb_task_A_Request_st::InternalSwap(atomic_service_mbsb_task_A_Request_st* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_A_Request_st, _impl_.number2_)
      + sizeof(atomic_service_mbsb_task_A_Request_st::_impl_.number2_)
      - PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_A_Request_st, _impl_.number1_)>(
          reinterpret_cast<char*>(&_impl_.number1_),
          reinterpret_cast<char*>(&other->_impl_.number1_));
}

::google::protobuf::Metadata atomic_service_mbsb_task_A_Request_st::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class atomic_service_mbsb_task_A_Reply_st::_Internal {
 public:
};

atomic_service_mbsb_task_A_Reply_st::atomic_service_mbsb_task_A_Reply_st(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Reply_st)
}
atomic_service_mbsb_task_A_Reply_st::atomic_service_mbsb_task_A_Reply_st(
    ::google::protobuf::Arena* arena, const atomic_service_mbsb_task_A_Reply_st& from)
    : atomic_service_mbsb_task_A_Reply_st(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE atomic_service_mbsb_task_A_Reply_st::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void atomic_service_mbsb_task_A_Reply_st::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, sum_result_),
           0,
           offsetof(Impl_, return_type_) -
               offsetof(Impl_, sum_result_) +
               sizeof(Impl_::return_type_));
}
atomic_service_mbsb_task_A_Reply_st::~atomic_service_mbsb_task_A_Reply_st() {
  // @@protoc_insertion_point(destructor:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Reply_st)
  SharedDtor(*this);
}
inline void atomic_service_mbsb_task_A_Reply_st::SharedDtor(MessageLite& self) {
  atomic_service_mbsb_task_A_Reply_st& this_ = static_cast<atomic_service_mbsb_task_A_Reply_st&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* atomic_service_mbsb_task_A_Reply_st::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) atomic_service_mbsb_task_A_Reply_st(arena);
}
constexpr auto atomic_service_mbsb_task_A_Reply_st::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(atomic_service_mbsb_task_A_Reply_st),
                                            alignof(atomic_service_mbsb_task_A_Reply_st));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull atomic_service_mbsb_task_A_Reply_st::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_atomic_service_mbsb_task_A_Reply_st_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &atomic_service_mbsb_task_A_Reply_st::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<atomic_service_mbsb_task_A_Reply_st>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &atomic_service_mbsb_task_A_Reply_st::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<atomic_service_mbsb_task_A_Reply_st>(), &atomic_service_mbsb_task_A_Reply_st::ByteSizeLong,
            &atomic_service_mbsb_task_A_Reply_st::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_A_Reply_st, _impl_._cached_size_),
        false,
    },
    &atomic_service_mbsb_task_A_Reply_st::kDescriptorMethods,
    &descriptor_table_atomic_5fservice_5fmbsb_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* atomic_service_mbsb_task_A_Reply_st::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> atomic_service_mbsb_task_A_Reply_st::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::atomic_service_mbsb_Package::atomic_service_mbsb_task_A_Reply_st>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 return_type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(atomic_service_mbsb_task_A_Reply_st, _impl_.return_type_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_A_Reply_st, _impl_.return_type_)}},
    // int32 sum_result = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(atomic_service_mbsb_task_A_Reply_st, _impl_.sum_result_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_A_Reply_st, _impl_.sum_result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 sum_result = 1;
    {PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_A_Reply_st, _impl_.sum_result_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 return_type = 2;
    {PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_A_Reply_st, _impl_.return_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void atomic_service_mbsb_task_A_Reply_st::Clear() {
// @@protoc_insertion_point(message_clear_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Reply_st)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.sum_result_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.return_type_) -
      reinterpret_cast<char*>(&_impl_.sum_result_)) + sizeof(_impl_.return_type_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* atomic_service_mbsb_task_A_Reply_st::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const atomic_service_mbsb_task_A_Reply_st& this_ = static_cast<const atomic_service_mbsb_task_A_Reply_st&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* atomic_service_mbsb_task_A_Reply_st::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const atomic_service_mbsb_task_A_Reply_st& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Reply_st)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 sum_result = 1;
          if (this_._internal_sum_result() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_sum_result(), target);
          }

          // int32 return_type = 2;
          if (this_._internal_return_type() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_return_type(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Reply_st)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t atomic_service_mbsb_task_A_Reply_st::ByteSizeLong(const MessageLite& base) {
          const atomic_service_mbsb_task_A_Reply_st& this_ = static_cast<const atomic_service_mbsb_task_A_Reply_st&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t atomic_service_mbsb_task_A_Reply_st::ByteSizeLong() const {
          const atomic_service_mbsb_task_A_Reply_st& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Reply_st)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 sum_result = 1;
            if (this_._internal_sum_result() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_sum_result());
            }
            // int32 return_type = 2;
            if (this_._internal_return_type() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_return_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void atomic_service_mbsb_task_A_Reply_st::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<atomic_service_mbsb_task_A_Reply_st*>(&to_msg);
  auto& from = static_cast<const atomic_service_mbsb_task_A_Reply_st&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Reply_st)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_sum_result() != 0) {
    _this->_impl_.sum_result_ = from._impl_.sum_result_;
  }
  if (from._internal_return_type() != 0) {
    _this->_impl_.return_type_ = from._impl_.return_type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void atomic_service_mbsb_task_A_Reply_st::CopyFrom(const atomic_service_mbsb_task_A_Reply_st& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Reply_st)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void atomic_service_mbsb_task_A_Reply_st::InternalSwap(atomic_service_mbsb_task_A_Reply_st* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_A_Reply_st, _impl_.return_type_)
      + sizeof(atomic_service_mbsb_task_A_Reply_st::_impl_.return_type_)
      - PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_A_Reply_st, _impl_.sum_result_)>(
          reinterpret_cast<char*>(&_impl_.sum_result_),
          reinterpret_cast<char*>(&other->_impl_.sum_result_));
}

::google::protobuf::Metadata atomic_service_mbsb_task_A_Reply_st::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class atomic_service_mbsb_task_B_Request_st::_Internal {
 public:
};

atomic_service_mbsb_task_B_Request_st::atomic_service_mbsb_task_B_Request_st(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Request_st)
}
atomic_service_mbsb_task_B_Request_st::atomic_service_mbsb_task_B_Request_st(
    ::google::protobuf::Arena* arena, const atomic_service_mbsb_task_B_Request_st& from)
    : atomic_service_mbsb_task_B_Request_st(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE atomic_service_mbsb_task_B_Request_st::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void atomic_service_mbsb_task_B_Request_st::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, number1_),
           0,
           offsetof(Impl_, number2_) -
               offsetof(Impl_, number1_) +
               sizeof(Impl_::number2_));
}
atomic_service_mbsb_task_B_Request_st::~atomic_service_mbsb_task_B_Request_st() {
  // @@protoc_insertion_point(destructor:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Request_st)
  SharedDtor(*this);
}
inline void atomic_service_mbsb_task_B_Request_st::SharedDtor(MessageLite& self) {
  atomic_service_mbsb_task_B_Request_st& this_ = static_cast<atomic_service_mbsb_task_B_Request_st&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* atomic_service_mbsb_task_B_Request_st::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) atomic_service_mbsb_task_B_Request_st(arena);
}
constexpr auto atomic_service_mbsb_task_B_Request_st::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(atomic_service_mbsb_task_B_Request_st),
                                            alignof(atomic_service_mbsb_task_B_Request_st));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull atomic_service_mbsb_task_B_Request_st::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_atomic_service_mbsb_task_B_Request_st_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &atomic_service_mbsb_task_B_Request_st::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<atomic_service_mbsb_task_B_Request_st>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &atomic_service_mbsb_task_B_Request_st::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<atomic_service_mbsb_task_B_Request_st>(), &atomic_service_mbsb_task_B_Request_st::ByteSizeLong,
            &atomic_service_mbsb_task_B_Request_st::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_B_Request_st, _impl_._cached_size_),
        false,
    },
    &atomic_service_mbsb_task_B_Request_st::kDescriptorMethods,
    &descriptor_table_atomic_5fservice_5fmbsb_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* atomic_service_mbsb_task_B_Request_st::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> atomic_service_mbsb_task_B_Request_st::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Request_st>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 number2 = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(atomic_service_mbsb_task_B_Request_st, _impl_.number2_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_B_Request_st, _impl_.number2_)}},
    // int32 number1 = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(atomic_service_mbsb_task_B_Request_st, _impl_.number1_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_B_Request_st, _impl_.number1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 number1 = 1;
    {PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_B_Request_st, _impl_.number1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 number2 = 2;
    {PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_B_Request_st, _impl_.number2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void atomic_service_mbsb_task_B_Request_st::Clear() {
// @@protoc_insertion_point(message_clear_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Request_st)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.number1_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.number2_) -
      reinterpret_cast<char*>(&_impl_.number1_)) + sizeof(_impl_.number2_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* atomic_service_mbsb_task_B_Request_st::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const atomic_service_mbsb_task_B_Request_st& this_ = static_cast<const atomic_service_mbsb_task_B_Request_st&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* atomic_service_mbsb_task_B_Request_st::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const atomic_service_mbsb_task_B_Request_st& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Request_st)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 number1 = 1;
          if (this_._internal_number1() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_number1(), target);
          }

          // int32 number2 = 2;
          if (this_._internal_number2() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_number2(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Request_st)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t atomic_service_mbsb_task_B_Request_st::ByteSizeLong(const MessageLite& base) {
          const atomic_service_mbsb_task_B_Request_st& this_ = static_cast<const atomic_service_mbsb_task_B_Request_st&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t atomic_service_mbsb_task_B_Request_st::ByteSizeLong() const {
          const atomic_service_mbsb_task_B_Request_st& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Request_st)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 number1 = 1;
            if (this_._internal_number1() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_number1());
            }
            // int32 number2 = 2;
            if (this_._internal_number2() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_number2());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void atomic_service_mbsb_task_B_Request_st::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<atomic_service_mbsb_task_B_Request_st*>(&to_msg);
  auto& from = static_cast<const atomic_service_mbsb_task_B_Request_st&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Request_st)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_number1() != 0) {
    _this->_impl_.number1_ = from._impl_.number1_;
  }
  if (from._internal_number2() != 0) {
    _this->_impl_.number2_ = from._impl_.number2_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void atomic_service_mbsb_task_B_Request_st::CopyFrom(const atomic_service_mbsb_task_B_Request_st& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Request_st)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void atomic_service_mbsb_task_B_Request_st::InternalSwap(atomic_service_mbsb_task_B_Request_st* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_B_Request_st, _impl_.number2_)
      + sizeof(atomic_service_mbsb_task_B_Request_st::_impl_.number2_)
      - PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_B_Request_st, _impl_.number1_)>(
          reinterpret_cast<char*>(&_impl_.number1_),
          reinterpret_cast<char*>(&other->_impl_.number1_));
}

::google::protobuf::Metadata atomic_service_mbsb_task_B_Request_st::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class atomic_service_mbsb_task_B_Reply_st::_Internal {
 public:
};

atomic_service_mbsb_task_B_Reply_st::atomic_service_mbsb_task_B_Reply_st(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Reply_st)
}
atomic_service_mbsb_task_B_Reply_st::atomic_service_mbsb_task_B_Reply_st(
    ::google::protobuf::Arena* arena, const atomic_service_mbsb_task_B_Reply_st& from)
    : atomic_service_mbsb_task_B_Reply_st(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE atomic_service_mbsb_task_B_Reply_st::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void atomic_service_mbsb_task_B_Reply_st::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, sub_result_),
           0,
           offsetof(Impl_, return_type_) -
               offsetof(Impl_, sub_result_) +
               sizeof(Impl_::return_type_));
}
atomic_service_mbsb_task_B_Reply_st::~atomic_service_mbsb_task_B_Reply_st() {
  // @@protoc_insertion_point(destructor:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Reply_st)
  SharedDtor(*this);
}
inline void atomic_service_mbsb_task_B_Reply_st::SharedDtor(MessageLite& self) {
  atomic_service_mbsb_task_B_Reply_st& this_ = static_cast<atomic_service_mbsb_task_B_Reply_st&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* atomic_service_mbsb_task_B_Reply_st::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) atomic_service_mbsb_task_B_Reply_st(arena);
}
constexpr auto atomic_service_mbsb_task_B_Reply_st::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(atomic_service_mbsb_task_B_Reply_st),
                                            alignof(atomic_service_mbsb_task_B_Reply_st));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull atomic_service_mbsb_task_B_Reply_st::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_atomic_service_mbsb_task_B_Reply_st_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &atomic_service_mbsb_task_B_Reply_st::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<atomic_service_mbsb_task_B_Reply_st>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &atomic_service_mbsb_task_B_Reply_st::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<atomic_service_mbsb_task_B_Reply_st>(), &atomic_service_mbsb_task_B_Reply_st::ByteSizeLong,
            &atomic_service_mbsb_task_B_Reply_st::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_B_Reply_st, _impl_._cached_size_),
        false,
    },
    &atomic_service_mbsb_task_B_Reply_st::kDescriptorMethods,
    &descriptor_table_atomic_5fservice_5fmbsb_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* atomic_service_mbsb_task_B_Reply_st::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> atomic_service_mbsb_task_B_Reply_st::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::atomic_service_mbsb_Package::atomic_service_mbsb_task_B_Reply_st>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 return_type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(atomic_service_mbsb_task_B_Reply_st, _impl_.return_type_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_B_Reply_st, _impl_.return_type_)}},
    // int32 sub_result = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(atomic_service_mbsb_task_B_Reply_st, _impl_.sub_result_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_B_Reply_st, _impl_.sub_result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 sub_result = 1;
    {PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_B_Reply_st, _impl_.sub_result_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 return_type = 2;
    {PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_B_Reply_st, _impl_.return_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void atomic_service_mbsb_task_B_Reply_st::Clear() {
// @@protoc_insertion_point(message_clear_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Reply_st)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.sub_result_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.return_type_) -
      reinterpret_cast<char*>(&_impl_.sub_result_)) + sizeof(_impl_.return_type_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* atomic_service_mbsb_task_B_Reply_st::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const atomic_service_mbsb_task_B_Reply_st& this_ = static_cast<const atomic_service_mbsb_task_B_Reply_st&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* atomic_service_mbsb_task_B_Reply_st::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const atomic_service_mbsb_task_B_Reply_st& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Reply_st)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 sub_result = 1;
          if (this_._internal_sub_result() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_sub_result(), target);
          }

          // int32 return_type = 2;
          if (this_._internal_return_type() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_return_type(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Reply_st)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t atomic_service_mbsb_task_B_Reply_st::ByteSizeLong(const MessageLite& base) {
          const atomic_service_mbsb_task_B_Reply_st& this_ = static_cast<const atomic_service_mbsb_task_B_Reply_st&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t atomic_service_mbsb_task_B_Reply_st::ByteSizeLong() const {
          const atomic_service_mbsb_task_B_Reply_st& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Reply_st)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 sub_result = 1;
            if (this_._internal_sub_result() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_sub_result());
            }
            // int32 return_type = 2;
            if (this_._internal_return_type() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_return_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void atomic_service_mbsb_task_B_Reply_st::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<atomic_service_mbsb_task_B_Reply_st*>(&to_msg);
  auto& from = static_cast<const atomic_service_mbsb_task_B_Reply_st&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Reply_st)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_sub_result() != 0) {
    _this->_impl_.sub_result_ = from._impl_.sub_result_;
  }
  if (from._internal_return_type() != 0) {
    _this->_impl_.return_type_ = from._impl_.return_type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void atomic_service_mbsb_task_B_Reply_st::CopyFrom(const atomic_service_mbsb_task_B_Reply_st& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Reply_st)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void atomic_service_mbsb_task_B_Reply_st::InternalSwap(atomic_service_mbsb_task_B_Reply_st* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_B_Reply_st, _impl_.return_type_)
      + sizeof(atomic_service_mbsb_task_B_Reply_st::_impl_.return_type_)
      - PROTOBUF_FIELD_OFFSET(atomic_service_mbsb_task_B_Reply_st, _impl_.sub_result_)>(
          reinterpret_cast<char*>(&_impl_.sub_result_),
          reinterpret_cast<char*>(&other->_impl_.sub_result_));
}

::google::protobuf::Metadata atomic_service_mbsb_task_B_Reply_st::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace atomic_service_mbsb_Package
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_atomic_5fservice_5fmbsb_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
