// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: atomic_service_mbsb.proto
// Protobuf C++ Version: 5.29.0

#ifndef atomic_5fservice_5fmbsb_2eproto_2epb_2eh
#define atomic_5fservice_5fmbsb_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_atomic_5fservice_5fmbsb_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_atomic_5fservice_5fmbsb_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_atomic_5fservice_5fmbsb_2eproto;
namespace atomic_service_mbsb_Package {
class atomic_service_mbsb_task_A_Reply_st;
struct atomic_service_mbsb_task_A_Reply_stDefaultTypeInternal;
extern atomic_service_mbsb_task_A_Reply_stDefaultTypeInternal _atomic_service_mbsb_task_A_Reply_st_default_instance_;
class atomic_service_mbsb_task_A_Request_st;
struct atomic_service_mbsb_task_A_Request_stDefaultTypeInternal;
extern atomic_service_mbsb_task_A_Request_stDefaultTypeInternal _atomic_service_mbsb_task_A_Request_st_default_instance_;
class atomic_service_mbsb_task_B_Reply_st;
struct atomic_service_mbsb_task_B_Reply_stDefaultTypeInternal;
extern atomic_service_mbsb_task_B_Reply_stDefaultTypeInternal _atomic_service_mbsb_task_B_Reply_st_default_instance_;
class atomic_service_mbsb_task_B_Request_st;
struct atomic_service_mbsb_task_B_Request_stDefaultTypeInternal;
extern atomic_service_mbsb_task_B_Request_stDefaultTypeInternal _atomic_service_mbsb_task_B_Request_st_default_instance_;
}  // namespace atomic_service_mbsb_Package
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace atomic_service_mbsb_Package {

// ===================================================================


// -------------------------------------------------------------------

class atomic_service_mbsb_task_B_Request_st final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Request_st) */ {
 public:
  inline atomic_service_mbsb_task_B_Request_st() : atomic_service_mbsb_task_B_Request_st(nullptr) {}
  ~atomic_service_mbsb_task_B_Request_st() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(atomic_service_mbsb_task_B_Request_st* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(atomic_service_mbsb_task_B_Request_st));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR atomic_service_mbsb_task_B_Request_st(
      ::google::protobuf::internal::ConstantInitialized);

  inline atomic_service_mbsb_task_B_Request_st(const atomic_service_mbsb_task_B_Request_st& from) : atomic_service_mbsb_task_B_Request_st(nullptr, from) {}
  inline atomic_service_mbsb_task_B_Request_st(atomic_service_mbsb_task_B_Request_st&& from) noexcept
      : atomic_service_mbsb_task_B_Request_st(nullptr, std::move(from)) {}
  inline atomic_service_mbsb_task_B_Request_st& operator=(const atomic_service_mbsb_task_B_Request_st& from) {
    CopyFrom(from);
    return *this;
  }
  inline atomic_service_mbsb_task_B_Request_st& operator=(atomic_service_mbsb_task_B_Request_st&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const atomic_service_mbsb_task_B_Request_st& default_instance() {
    return *internal_default_instance();
  }
  static inline const atomic_service_mbsb_task_B_Request_st* internal_default_instance() {
    return reinterpret_cast<const atomic_service_mbsb_task_B_Request_st*>(
        &_atomic_service_mbsb_task_B_Request_st_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(atomic_service_mbsb_task_B_Request_st& a, atomic_service_mbsb_task_B_Request_st& b) { a.Swap(&b); }
  inline void Swap(atomic_service_mbsb_task_B_Request_st* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(atomic_service_mbsb_task_B_Request_st* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  atomic_service_mbsb_task_B_Request_st* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<atomic_service_mbsb_task_B_Request_st>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const atomic_service_mbsb_task_B_Request_st& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const atomic_service_mbsb_task_B_Request_st& from) { atomic_service_mbsb_task_B_Request_st::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(atomic_service_mbsb_task_B_Request_st* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Request_st"; }

 protected:
  explicit atomic_service_mbsb_task_B_Request_st(::google::protobuf::Arena* arena);
  atomic_service_mbsb_task_B_Request_st(::google::protobuf::Arena* arena, const atomic_service_mbsb_task_B_Request_st& from);
  atomic_service_mbsb_task_B_Request_st(::google::protobuf::Arena* arena, atomic_service_mbsb_task_B_Request_st&& from) noexcept
      : atomic_service_mbsb_task_B_Request_st(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNumber1FieldNumber = 1,
    kNumber2FieldNumber = 2,
  };
  // int32 number1 = 1;
  void clear_number1() ;
  ::int32_t number1() const;
  void set_number1(::int32_t value);

  private:
  ::int32_t _internal_number1() const;
  void _internal_set_number1(::int32_t value);

  public:
  // int32 number2 = 2;
  void clear_number2() ;
  ::int32_t number2() const;
  void set_number2(::int32_t value);

  private:
  ::int32_t _internal_number2() const;
  void _internal_set_number2(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Request_st)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const atomic_service_mbsb_task_B_Request_st& from_msg);
    ::int32_t number1_;
    ::int32_t number2_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_atomic_5fservice_5fmbsb_2eproto;
};
// -------------------------------------------------------------------

class atomic_service_mbsb_task_B_Reply_st final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Reply_st) */ {
 public:
  inline atomic_service_mbsb_task_B_Reply_st() : atomic_service_mbsb_task_B_Reply_st(nullptr) {}
  ~atomic_service_mbsb_task_B_Reply_st() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(atomic_service_mbsb_task_B_Reply_st* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(atomic_service_mbsb_task_B_Reply_st));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR atomic_service_mbsb_task_B_Reply_st(
      ::google::protobuf::internal::ConstantInitialized);

  inline atomic_service_mbsb_task_B_Reply_st(const atomic_service_mbsb_task_B_Reply_st& from) : atomic_service_mbsb_task_B_Reply_st(nullptr, from) {}
  inline atomic_service_mbsb_task_B_Reply_st(atomic_service_mbsb_task_B_Reply_st&& from) noexcept
      : atomic_service_mbsb_task_B_Reply_st(nullptr, std::move(from)) {}
  inline atomic_service_mbsb_task_B_Reply_st& operator=(const atomic_service_mbsb_task_B_Reply_st& from) {
    CopyFrom(from);
    return *this;
  }
  inline atomic_service_mbsb_task_B_Reply_st& operator=(atomic_service_mbsb_task_B_Reply_st&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const atomic_service_mbsb_task_B_Reply_st& default_instance() {
    return *internal_default_instance();
  }
  static inline const atomic_service_mbsb_task_B_Reply_st* internal_default_instance() {
    return reinterpret_cast<const atomic_service_mbsb_task_B_Reply_st*>(
        &_atomic_service_mbsb_task_B_Reply_st_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(atomic_service_mbsb_task_B_Reply_st& a, atomic_service_mbsb_task_B_Reply_st& b) { a.Swap(&b); }
  inline void Swap(atomic_service_mbsb_task_B_Reply_st* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(atomic_service_mbsb_task_B_Reply_st* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  atomic_service_mbsb_task_B_Reply_st* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<atomic_service_mbsb_task_B_Reply_st>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const atomic_service_mbsb_task_B_Reply_st& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const atomic_service_mbsb_task_B_Reply_st& from) { atomic_service_mbsb_task_B_Reply_st::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(atomic_service_mbsb_task_B_Reply_st* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Reply_st"; }

 protected:
  explicit atomic_service_mbsb_task_B_Reply_st(::google::protobuf::Arena* arena);
  atomic_service_mbsb_task_B_Reply_st(::google::protobuf::Arena* arena, const atomic_service_mbsb_task_B_Reply_st& from);
  atomic_service_mbsb_task_B_Reply_st(::google::protobuf::Arena* arena, atomic_service_mbsb_task_B_Reply_st&& from) noexcept
      : atomic_service_mbsb_task_B_Reply_st(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSubResultFieldNumber = 1,
    kReturnTypeFieldNumber = 2,
  };
  // int32 sub_result = 1;
  void clear_sub_result() ;
  ::int32_t sub_result() const;
  void set_sub_result(::int32_t value);

  private:
  ::int32_t _internal_sub_result() const;
  void _internal_set_sub_result(::int32_t value);

  public:
  // int32 return_type = 2;
  void clear_return_type() ;
  ::int32_t return_type() const;
  void set_return_type(::int32_t value);

  private:
  ::int32_t _internal_return_type() const;
  void _internal_set_return_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Reply_st)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const atomic_service_mbsb_task_B_Reply_st& from_msg);
    ::int32_t sub_result_;
    ::int32_t return_type_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_atomic_5fservice_5fmbsb_2eproto;
};
// -------------------------------------------------------------------

class atomic_service_mbsb_task_A_Request_st final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Request_st) */ {
 public:
  inline atomic_service_mbsb_task_A_Request_st() : atomic_service_mbsb_task_A_Request_st(nullptr) {}
  ~atomic_service_mbsb_task_A_Request_st() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(atomic_service_mbsb_task_A_Request_st* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(atomic_service_mbsb_task_A_Request_st));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR atomic_service_mbsb_task_A_Request_st(
      ::google::protobuf::internal::ConstantInitialized);

  inline atomic_service_mbsb_task_A_Request_st(const atomic_service_mbsb_task_A_Request_st& from) : atomic_service_mbsb_task_A_Request_st(nullptr, from) {}
  inline atomic_service_mbsb_task_A_Request_st(atomic_service_mbsb_task_A_Request_st&& from) noexcept
      : atomic_service_mbsb_task_A_Request_st(nullptr, std::move(from)) {}
  inline atomic_service_mbsb_task_A_Request_st& operator=(const atomic_service_mbsb_task_A_Request_st& from) {
    CopyFrom(from);
    return *this;
  }
  inline atomic_service_mbsb_task_A_Request_st& operator=(atomic_service_mbsb_task_A_Request_st&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const atomic_service_mbsb_task_A_Request_st& default_instance() {
    return *internal_default_instance();
  }
  static inline const atomic_service_mbsb_task_A_Request_st* internal_default_instance() {
    return reinterpret_cast<const atomic_service_mbsb_task_A_Request_st*>(
        &_atomic_service_mbsb_task_A_Request_st_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(atomic_service_mbsb_task_A_Request_st& a, atomic_service_mbsb_task_A_Request_st& b) { a.Swap(&b); }
  inline void Swap(atomic_service_mbsb_task_A_Request_st* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(atomic_service_mbsb_task_A_Request_st* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  atomic_service_mbsb_task_A_Request_st* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<atomic_service_mbsb_task_A_Request_st>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const atomic_service_mbsb_task_A_Request_st& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const atomic_service_mbsb_task_A_Request_st& from) { atomic_service_mbsb_task_A_Request_st::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(atomic_service_mbsb_task_A_Request_st* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Request_st"; }

 protected:
  explicit atomic_service_mbsb_task_A_Request_st(::google::protobuf::Arena* arena);
  atomic_service_mbsb_task_A_Request_st(::google::protobuf::Arena* arena, const atomic_service_mbsb_task_A_Request_st& from);
  atomic_service_mbsb_task_A_Request_st(::google::protobuf::Arena* arena, atomic_service_mbsb_task_A_Request_st&& from) noexcept
      : atomic_service_mbsb_task_A_Request_st(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNumber1FieldNumber = 1,
    kNumber2FieldNumber = 2,
  };
  // int32 number1 = 1;
  void clear_number1() ;
  ::int32_t number1() const;
  void set_number1(::int32_t value);

  private:
  ::int32_t _internal_number1() const;
  void _internal_set_number1(::int32_t value);

  public:
  // int32 number2 = 2;
  void clear_number2() ;
  ::int32_t number2() const;
  void set_number2(::int32_t value);

  private:
  ::int32_t _internal_number2() const;
  void _internal_set_number2(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Request_st)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const atomic_service_mbsb_task_A_Request_st& from_msg);
    ::int32_t number1_;
    ::int32_t number2_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_atomic_5fservice_5fmbsb_2eproto;
};
// -------------------------------------------------------------------

class atomic_service_mbsb_task_A_Reply_st final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Reply_st) */ {
 public:
  inline atomic_service_mbsb_task_A_Reply_st() : atomic_service_mbsb_task_A_Reply_st(nullptr) {}
  ~atomic_service_mbsb_task_A_Reply_st() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(atomic_service_mbsb_task_A_Reply_st* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(atomic_service_mbsb_task_A_Reply_st));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR atomic_service_mbsb_task_A_Reply_st(
      ::google::protobuf::internal::ConstantInitialized);

  inline atomic_service_mbsb_task_A_Reply_st(const atomic_service_mbsb_task_A_Reply_st& from) : atomic_service_mbsb_task_A_Reply_st(nullptr, from) {}
  inline atomic_service_mbsb_task_A_Reply_st(atomic_service_mbsb_task_A_Reply_st&& from) noexcept
      : atomic_service_mbsb_task_A_Reply_st(nullptr, std::move(from)) {}
  inline atomic_service_mbsb_task_A_Reply_st& operator=(const atomic_service_mbsb_task_A_Reply_st& from) {
    CopyFrom(from);
    return *this;
  }
  inline atomic_service_mbsb_task_A_Reply_st& operator=(atomic_service_mbsb_task_A_Reply_st&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const atomic_service_mbsb_task_A_Reply_st& default_instance() {
    return *internal_default_instance();
  }
  static inline const atomic_service_mbsb_task_A_Reply_st* internal_default_instance() {
    return reinterpret_cast<const atomic_service_mbsb_task_A_Reply_st*>(
        &_atomic_service_mbsb_task_A_Reply_st_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(atomic_service_mbsb_task_A_Reply_st& a, atomic_service_mbsb_task_A_Reply_st& b) { a.Swap(&b); }
  inline void Swap(atomic_service_mbsb_task_A_Reply_st* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(atomic_service_mbsb_task_A_Reply_st* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  atomic_service_mbsb_task_A_Reply_st* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<atomic_service_mbsb_task_A_Reply_st>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const atomic_service_mbsb_task_A_Reply_st& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const atomic_service_mbsb_task_A_Reply_st& from) { atomic_service_mbsb_task_A_Reply_st::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(atomic_service_mbsb_task_A_Reply_st* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Reply_st"; }

 protected:
  explicit atomic_service_mbsb_task_A_Reply_st(::google::protobuf::Arena* arena);
  atomic_service_mbsb_task_A_Reply_st(::google::protobuf::Arena* arena, const atomic_service_mbsb_task_A_Reply_st& from);
  atomic_service_mbsb_task_A_Reply_st(::google::protobuf::Arena* arena, atomic_service_mbsb_task_A_Reply_st&& from) noexcept
      : atomic_service_mbsb_task_A_Reply_st(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSumResultFieldNumber = 1,
    kReturnTypeFieldNumber = 2,
  };
  // int32 sum_result = 1;
  void clear_sum_result() ;
  ::int32_t sum_result() const;
  void set_sum_result(::int32_t value);

  private:
  ::int32_t _internal_sum_result() const;
  void _internal_set_sum_result(::int32_t value);

  public:
  // int32 return_type = 2;
  void clear_return_type() ;
  ::int32_t return_type() const;
  void set_return_type(::int32_t value);

  private:
  ::int32_t _internal_return_type() const;
  void _internal_set_return_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Reply_st)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const atomic_service_mbsb_task_A_Reply_st& from_msg);
    ::int32_t sum_result_;
    ::int32_t return_type_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_atomic_5fservice_5fmbsb_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// atomic_service_mbsb_task_A_Request_st

// int32 number1 = 1;
inline void atomic_service_mbsb_task_A_Request_st::clear_number1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.number1_ = 0;
}
inline ::int32_t atomic_service_mbsb_task_A_Request_st::number1() const {
  // @@protoc_insertion_point(field_get:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Request_st.number1)
  return _internal_number1();
}
inline void atomic_service_mbsb_task_A_Request_st::set_number1(::int32_t value) {
  _internal_set_number1(value);
  // @@protoc_insertion_point(field_set:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Request_st.number1)
}
inline ::int32_t atomic_service_mbsb_task_A_Request_st::_internal_number1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.number1_;
}
inline void atomic_service_mbsb_task_A_Request_st::_internal_set_number1(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.number1_ = value;
}

// int32 number2 = 2;
inline void atomic_service_mbsb_task_A_Request_st::clear_number2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.number2_ = 0;
}
inline ::int32_t atomic_service_mbsb_task_A_Request_st::number2() const {
  // @@protoc_insertion_point(field_get:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Request_st.number2)
  return _internal_number2();
}
inline void atomic_service_mbsb_task_A_Request_st::set_number2(::int32_t value) {
  _internal_set_number2(value);
  // @@protoc_insertion_point(field_set:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Request_st.number2)
}
inline ::int32_t atomic_service_mbsb_task_A_Request_st::_internal_number2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.number2_;
}
inline void atomic_service_mbsb_task_A_Request_st::_internal_set_number2(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.number2_ = value;
}

// -------------------------------------------------------------------

// atomic_service_mbsb_task_A_Reply_st

// int32 sum_result = 1;
inline void atomic_service_mbsb_task_A_Reply_st::clear_sum_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sum_result_ = 0;
}
inline ::int32_t atomic_service_mbsb_task_A_Reply_st::sum_result() const {
  // @@protoc_insertion_point(field_get:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Reply_st.sum_result)
  return _internal_sum_result();
}
inline void atomic_service_mbsb_task_A_Reply_st::set_sum_result(::int32_t value) {
  _internal_set_sum_result(value);
  // @@protoc_insertion_point(field_set:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Reply_st.sum_result)
}
inline ::int32_t atomic_service_mbsb_task_A_Reply_st::_internal_sum_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sum_result_;
}
inline void atomic_service_mbsb_task_A_Reply_st::_internal_set_sum_result(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sum_result_ = value;
}

// int32 return_type = 2;
inline void atomic_service_mbsb_task_A_Reply_st::clear_return_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.return_type_ = 0;
}
inline ::int32_t atomic_service_mbsb_task_A_Reply_st::return_type() const {
  // @@protoc_insertion_point(field_get:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Reply_st.return_type)
  return _internal_return_type();
}
inline void atomic_service_mbsb_task_A_Reply_st::set_return_type(::int32_t value) {
  _internal_set_return_type(value);
  // @@protoc_insertion_point(field_set:atomic_service_mbsb_Package.atomic_service_mbsb_task_A_Reply_st.return_type)
}
inline ::int32_t atomic_service_mbsb_task_A_Reply_st::_internal_return_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.return_type_;
}
inline void atomic_service_mbsb_task_A_Reply_st::_internal_set_return_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.return_type_ = value;
}

// -------------------------------------------------------------------

// atomic_service_mbsb_task_B_Request_st

// int32 number1 = 1;
inline void atomic_service_mbsb_task_B_Request_st::clear_number1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.number1_ = 0;
}
inline ::int32_t atomic_service_mbsb_task_B_Request_st::number1() const {
  // @@protoc_insertion_point(field_get:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Request_st.number1)
  return _internal_number1();
}
inline void atomic_service_mbsb_task_B_Request_st::set_number1(::int32_t value) {
  _internal_set_number1(value);
  // @@protoc_insertion_point(field_set:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Request_st.number1)
}
inline ::int32_t atomic_service_mbsb_task_B_Request_st::_internal_number1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.number1_;
}
inline void atomic_service_mbsb_task_B_Request_st::_internal_set_number1(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.number1_ = value;
}

// int32 number2 = 2;
inline void atomic_service_mbsb_task_B_Request_st::clear_number2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.number2_ = 0;
}
inline ::int32_t atomic_service_mbsb_task_B_Request_st::number2() const {
  // @@protoc_insertion_point(field_get:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Request_st.number2)
  return _internal_number2();
}
inline void atomic_service_mbsb_task_B_Request_st::set_number2(::int32_t value) {
  _internal_set_number2(value);
  // @@protoc_insertion_point(field_set:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Request_st.number2)
}
inline ::int32_t atomic_service_mbsb_task_B_Request_st::_internal_number2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.number2_;
}
inline void atomic_service_mbsb_task_B_Request_st::_internal_set_number2(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.number2_ = value;
}

// -------------------------------------------------------------------

// atomic_service_mbsb_task_B_Reply_st

// int32 sub_result = 1;
inline void atomic_service_mbsb_task_B_Reply_st::clear_sub_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sub_result_ = 0;
}
inline ::int32_t atomic_service_mbsb_task_B_Reply_st::sub_result() const {
  // @@protoc_insertion_point(field_get:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Reply_st.sub_result)
  return _internal_sub_result();
}
inline void atomic_service_mbsb_task_B_Reply_st::set_sub_result(::int32_t value) {
  _internal_set_sub_result(value);
  // @@protoc_insertion_point(field_set:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Reply_st.sub_result)
}
inline ::int32_t atomic_service_mbsb_task_B_Reply_st::_internal_sub_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sub_result_;
}
inline void atomic_service_mbsb_task_B_Reply_st::_internal_set_sub_result(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sub_result_ = value;
}

// int32 return_type = 2;
inline void atomic_service_mbsb_task_B_Reply_st::clear_return_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.return_type_ = 0;
}
inline ::int32_t atomic_service_mbsb_task_B_Reply_st::return_type() const {
  // @@protoc_insertion_point(field_get:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Reply_st.return_type)
  return _internal_return_type();
}
inline void atomic_service_mbsb_task_B_Reply_st::set_return_type(::int32_t value) {
  _internal_set_return_type(value);
  // @@protoc_insertion_point(field_set:atomic_service_mbsb_Package.atomic_service_mbsb_task_B_Reply_st.return_type)
}
inline ::int32_t atomic_service_mbsb_task_B_Reply_st::_internal_return_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.return_type_;
}
inline void atomic_service_mbsb_task_B_Reply_st::_internal_set_return_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.return_type_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace atomic_service_mbsb_Package


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // atomic_5fservice_5fmbsb_2eproto_2epb_2eh
