/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /root/atom_service_dev/server_compiling/db/client/plane/idl/endResponseSF/endResponseSF.h
  Source: /root/atom_service_dev/server_compiling/db/client/plane/idl/endResponseSF/endResponseSF.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC__ROOT_ATOM_SERVICE_DEV_SERVER_COMPILING_DB_CLIENT_PLANE_IDL_ENDRESPONSESF_ENDRESPONSESF_H_728A08C3F44B29D1A3C6777352C24E71
#define DDSC__ROOT_ATOM_SERVICE_DEV_SERVER_COMPILING_DB_CLIENT_PLANE_IDL_ENDRESPONSESF_ENDRESPONSESF_H_728A08C3F44B29D1A3C6777352C24E71

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct endResponseSF_release_result
{
  int32_t x;
  int32_t y;
  int32_t z;
  int32_t return_type;
} endResponseSF_release_result;

extern const dds_topic_descriptor_t endResponseSF_release_result_desc;

#define endResponseSF_release_result__alloc() \
((endResponseSF_release_result*) dds_alloc (sizeof (endResponseSF_release_result)));

#define endResponseSF_release_result_free(d,o) \
dds_sample_free ((d), &endResponseSF_release_result_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__ROOT_ATOM_SERVICE_DEV_SERVER_COMPILING_DB_CLIENT_PLANE_IDL_ENDRESPONSESF_ENDRESPONSESF_H_728A08C3F44B29D1A3C6777352C24E71 */
