// write for formal test

module FormalRequest
{
  struct Request
  {
    long number1;
    long number2;
    double doubleNumber1;
    double doubleNumber2;
    string message1;
    string message2;
  };
};
